#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#
#  Copyright 2013 stsouko <stsouko@live.ru>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#
#
__author__ = 'stsouko'
import sys
import os
import re


def main():
    if len(sys.argv) < 2:
        sys.exit('а файл угадать мне?')
    if not os.path.exists(sys.argv[1]):
        sys.exit('нихт файл' % sys.argv[1])

    print "%NProcShared=4\n" \
          "#n PM3 Opt Freq\n\n" \
          "autogenerated from priroda mol\n\n" \
          "0 1"
    for line in open(sys.argv[1]):
        cord = re.search('[0-9]{1,3}(\s+-?[0-9]+\.[0-9]+){3}', line)
        if cord:
            print cord.group()
    print "\n"
    return 0


if __name__ == '__main__':
    main()